#!/bin/sh

# Abort on failure.
set -e

# Mount cgroups.
mount -t cgroup2 none /sys/fs/cgroup
# Create /dev/shm for podman locks.
mkdir -p /dev/shm
mount -t tmpfs none /dev/shm

# Cleanup after reboot.
rm -rf /storage/containers/run
rm -rf /storage/containers/net
rm -rf /var/lib/cni
# Create the necessary directories in storage.
mkdir -p /storage/containers/run
mkdir -p /storage/containers/graph
mkdir -p /storage/containers/graph/tmp
mkdir -p /storage/containers/net

# Update TUN device permissions.
chmod 0666 /dev/net/tun

# Migrate existing containers if needed (e.g. when using persistent storage).
podman system migrate
podman system prune --external

# Use podman-compose to start up containers when defined.
if [ -d "/etc/oasis/containers" ]; then
	cd /etc/oasis/containers
	podman-compose up --detach --remove-orphans --force-recreate &
fi
